################################################################################
# DFRobot Firebeetle 2 ESP 32 S3 N16R8 Board
################################################################################
# Usage:
#   Add the following code to package section in the device file
# ------------------------------------------------------------------------------
# packages:
#   board: !include board/esp32/s3_firebeetle_2.yaml
# ------------------------------------------------------------------------------
# Author: Pascal Parent
# Company: Home Automator (ZA)
# Web: https://www.youtube.com/@homeautomatorza
# Version: 1.0.0
# Licence: CCO 1.0 https://creativecommons.org/publicdomain/zero/1.0/
# ------------------------------------------------------------------------------
# Notes: 
#       - Status LED is tied to the display backlight
#         Use: 
#             status_led:
#               - id: !remove ${device_internal_name}_status_led
#         To use display backlight.
#       - Right button is on GPIO47
# ------------------------------------------------------------------------------
# WARNING:
# This code carries a "It works on my setup" disclaimer!
# Meaning that it works on my setup but it may not work on yours.
# Use at your own risks!
################################################################################
esp32:
  board: dfrobot_firebeetle2_esp32s3
  framework:
    type: esp-idf
    version: 5.2.1 
    platform_version: 6.6.0 
    sdkconfig_options:
      CONFIG_OPENTHREAD_ENABLED: n      # Disable Thread!
      CONFIG_ENABLE_WIFI_STATION: y     # Ensures the WiFi is up
      CONFIG_USE_MINIMAL_MDNS: y
  flash_size: 16MB

esphome: 
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.arduino.memory_type: qio_opi

# PSRAM
psram:
  mode: octal
  speed: 80MHz

# I2C settings
i2c:
  - id: ${device_internal_name}_i2c_bus0
    sda: GPIO1
    scl: GPIO2
    scan: true

# UART
uart:
  - id: ${device_internal_name}_uart_bus0
    tx_pin: GPIO43
    rx_pin: GPIO44
    baud_rate: 256000
    parity: NONE
    stop_bits: 1

# SPI
spi:
  id: ${device_internal_name}_spi_bus0
  clk_pin: GPIO17
  mosi_pin: GPIO15
  miso_pin: GPIO16
  interface: hardware

# Status led
status_led:
  id: ${device_internal_name}_status_led
  pin:
    number: GPIO21
    inverted: false

# Sensors
sensor:
  # Internal Temperature Sensor
  - platform: internal_temperature
    id: ${device_internal_name}_internal_temperature
    name: Internal Temperature 
    icon: mdi:coolant-temperature
    unit_of_measurement: °C
    device_class: temperature
    update_interval: ${device_sampling_time}
    disabled_by_default: true
  
  - platform: template
    id: ${device_internal_name}_internal_temperature_f
    name: Internal Temperature (F)
    icon: mdi:coolant-temperature
    unit_of_measurement: °F
    lambda: return id(${device_internal_name}_internal_temperature).state * 9/5+32;
    device_class: temperature
    update_interval: ${device_sampling_time}
    entity_category: diagnostic
    disabled_by_default: true